In [1]:
num = int(input('Enter the Loan required ') )
i=0
while i<num:
    print(i*i)
    i=i+1

Enter the Loan required  ww

ValueError: invalid literal for int() with base 10: 'ww'

In [ ]:
num = int(input('Enter the Loan required ') )
num2=num+num
print(num2)

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# Numerical and Data Analysis 
import numpy as np 
import pandas as pd 
# Data Visualization 
import seaborn as sns 
import matplotlib.pyplot as plt 
# Extra - To Suppress warnings 
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df =pd.read_csv('Code_practice/popularity.csv')

In [ ]:
df.head()

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df['

In [ ]:
# Convert features to catagorical variables

In [4]:
dd2=pd.read_csv('Code_practice/popularity (1).csv')

In [5]:
dd2.describe()

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
count,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,...,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000
mean,354.530471,10.398749,546.514731,0.548216,0.996469,0.689175,10.883690,3.293638,4.544143,1.249874,...,0.095446,0.756728,-0.259524,-0.521944,-0.107500,0.282353,0.071425,0.341843,0.156064,3395.380184
std,214.163767,2.114037,471.107508,3.520708,5.231231,3.264816,11.332017,3.855141,8.309434,4.107855,...,0.071315,0.247786,0.127726,0.290290,0.095373,0.324247,0.265450,0.188791,0.226294,11626.950749
min,8.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,1.000000
25%,164.000000,9.000000,246.000000,0.470870,1.000000,0.625739,4.000000,1.000000,1.000000,0.000000,...,0.050000,0.600000,-0.328383,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000,946.000000
50%,339.000000,10.000000,409.000000,0.539226,1.000000,0.690476,8.000000,3.000000,1.000000,0.000000,...,0.100000,0.800000,-0.253333,-0.500000,-0.100000,0.150000,0.000000,0.500000,0.000000,1400.000000
75%,542.000000,12.000000,716.000000,0.608696,1.000000,0.754630,14.000000,4.000000,4.000000,1.000000,...,0.100000,1.000000,-0.186905,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000,2800.000000
max,731.000000,23.000000,8474.000000,701.000000,1042.000000,650.000000,304.000000,116.000000,128.000000,91.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000,843300.000000

In [7]:
dd2=pd.read_csv('/Users/anandjha/PycharmProjects/Road_map_to_GenAI_ML_2024/Code_practice/currencies.csv')
dd2

,Currency,Chinese Yuan,Euro,Japanese Yen,U.K. Pound Sterling,U.S. Dollar,Algerian Dinar,Australian Dollar,Bahrain Dinar,Botswana Pula,...,South African Rand,Sri Lanka Rupee,Swedish Krona,Swiss Franc,Thai Baht,Trinidad And Tobago Dollar,Tunisian Dinar,U.A.E. Dirham,Peso Uruguayo,Bolivar Fuerte
0,"July 01, 2016",9.29446,1.25367,143.645,1.05054,1.39596,NaN,1.87126,0.524882,NaN,...,20.3528,202.763,11.8246,1.36009,NaN,9.28428,3.06035,5.12668,NaN,13.9247
1,"July 05, 2016",9.31515,1.25322,142.715,1.06143,1.39684,154.063,1.85825,0.525213,15.2162,...,20.6240,202.886,11.7627,1.35689,49.0655,9.26724,NaN,5.12992,42.9026,13.9335
2,"July 06, 2016",9.31697,1.25834,140.540,1.07300,1.39286,154.094,1.87313,0.523717,15.2392,...,20.7232,NaN,11.8805,1.36208,49.0692,9.25643,NaN,5.11527,42.6425,13.8938
3,"July 07, 2016",9.31315,1.25737,140.640,1.06911,1.39316,153.957,1.85236,0.523829,15.1430,...,20.4288,202.351,11.9192,1.36098,49.0295,NaN,NaN,5.11637,42.4176,13.8968
4,"July 08, 2016",9.31350,1.25797,140.510,1.07261,1.39257,154.062,1.85974,0.523607,15.1202,...,20.6063,202.271,11.9327,1.36472,49.0408,9.26432,NaN,5.11423,42.2060,13.8909
5,"July 11, 2016",9.29403,1.25769,139.962,1.07050,1.38962,153.742,1.83836,0.522496,15.0067,...,20.0773,201.842,11.9439,1.36641,48.7950,9.23745,3.07068,5.10337,NaN,13.8614
6,"July 12, 2016",9.31021,1.25490,143.369,1.05762,1.39194,153.869,1.83439,0.523368,14.9510,...,19.9238,202.179,11.8614,1.36674,48.9182,9.28617,3.07901,5.11187,NaN,13.8845
7,"July 13, 2016",9.31350,1.25716,145.178,1.04680,1.39193,153.855,1.83101,0.523366,14.9509,...,19.9273,202.175,11.9234,1.37063,48.9958,9.29005,3.06884,5.11187,42.1644,13.8845
8,"July 14, 2016",9.30432,1.24695,144.895,1.05236,1.39122,153.763,1.82791,0.523097,14.9112,...,19.8519,202.074,11.8098,1.36326,48.8873,9.29990,NaN,5.10926,NaN,13.8774
9,"July 15, 2016",9.31532,1.25263,147.268,1.04242,1.39392,NaN,1.82786,0.524115,14.9723,...,20.0040,202.467,11.8409,1.36451,48.7607,9.31437,NaN,5.11917,42.0267,13.9044
10,"July 18, 2016",9.30354,1.25652,NaN,1.04952,1.38883,153.648,1.82741,0.522201,NaN,...,19.8556,201.728,NaN,1.36647,NaN,9.28514,3.06822,5.10048,NaN,13.8536

In [8]:
dd2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 52 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Currency                    11 non-null     object
 1   Chinese Yuan                11 non-null     float64
 2   Euro                        11 non-null     float64
 3   Japanese Yen                10 non-null     float64
 4   U.K. Pound Sterling         11 non-null     float64
 5   U.S. Dollar                 11 non-null     float64
 6   Algerian Dinar              9 non-null      float64
 7   Australian Dollar           11 non-null     float64
 8   Bahrain Dinar               11 non-null     float64
 9   Botswana Pula               9 non-null      float64
 10  Brazilian Real              11 non-null     float64
 11  Brunei Dollar               10 non-null     float64
 12  Canadian Dollar             10 non-null     float64
 13  Chilean Peso                11 non-null     float64
 14  Colombian Peso              11 non-null     object
 15  Czech Koruna                8 non-null      float64
 16  Danish Krone                11 non-null     float64
 17  Hungarian Forint            11 non-null     float64
 18  Icelandic Krona             11 non-null     float64
 19  Indian Rupee                9 non-null      float64
 20  Indonesian Rupiah           7 non-null      object
 21  Iranian Rial                6 non-null      object
 22  Israeli New Sheqel          11 non-null     float64
 23  Kazakhstani Tenge           8 non-null      float64
 24  Korean Won                  11 non-null     object
 25  Kuwaiti Dinar               6 non-null      float64
 26  Libyan Dinar                11 non-null     float64
 27  Malaysian Ringgit           8 non-null      float64
 28  Mauritian Rupee             9 non-null      float64
 29  Mexican Peso                11 non-null     float64
 30  Nepalese Rupee              11 non-null     float64
 31  New Zealand Dollar          11 non-null     float64
 32  Norwegian Krone             11 non-null     float64
 33  Rial Omani                  11 non-null     float64
 34  Pakistani Rupee             5 non-null      float64
 35  Nuevo Sol                   7 non-null      float64
 36  Philippine Peso             10 non-null     float64
 37  Polish Zloty                11 non-null     float64
 38  Qatar Riyal                 11 non-null     float64
 39  Russian Ruble               10 non-null     float64
 40  Saudi Arabian Riyal         11 non-null     float64
 41  Singapore Dollar            10 non-null     float64
 42  South African Rand          11 non-null     float64
 43  Sri Lanka Rupee             10 non-null     float64
 44  Swedish Krona               10 non-null     float64
 45  Swiss Franc                 11 non-null     float64
 46  Thai Baht                   9 non-null      float64
 47  Trinidad And Tobago Dollar  10 non-null     float64
 48  Tunisian Dinar              5 non-null      float64
 49  U.A.E. Dirham               11 non-null     float64
 50  Peso Uruguayo               6 non-null      float64
 51  Bolivar Fuerte              11 non-null     float64
dtypes: float64(47), object(5)
memory usage: 4.6+ KB

In [9]:
dd2.describe()

,Chinese Yuan,Euro,Japanese Yen,U.K. Pound Sterling,U.S. Dollar,Algerian Dinar,Australian Dollar,Bahrain Dinar,Botswana Pula,Brazilian Real,...,South African Rand,Sri Lanka Rupee,Swedish Krona,Swiss Franc,Thai Baht,Trinidad And Tobago Dollar,Tunisian Dinar,U.A.E. Dirham,Peso Uruguayo,Bolivar Fuerte
count,11.000000,11.000000,10.000000,11.000000,11.000000,9.000000,11.000000,11.000000,9.000000,11.000000,...,11.000000,10.000000,10.000000,11.000000,9.000000,10.000000,5.000000,11.000000,6.000000,11.000000
mean,9.308559,1.255129,142.872200,1.058719,1.392623,153.894778,1.845607,0.523626,15.056744,4.565969,...,20.215909,202.273600,11.869910,1.363889,48.951333,9.278535,3.069420,5.114408,42.393300,13.891409
std,0.008280,0.003391,2.451108,0.011189,0.002393,0.159560,0.017809,0.000900,0.124190,0.050809,...,0.336959,0.365212,0.060456,0.003784,0.116725,0.022396,0.006663,0.008796,0.329833,0.023886
min,9.294030,1.246950,139.962000,1.042420,1.388830,153.648000,1.827410,0.522201,14.911200,4.479930,...,19.851900,201.728000,11.762700,1.356890,48.760700,9.237450,3.060350,5.100480,42.026700,13.853600
25%,9.303930,1.253445,140.565000,1.050030,1.391575,153.763000,1.829460,0.523232,14.951000,4.535320,...,19.925550,202.099250,11.828675,1.361530,48.887300,9.265050,3.068220,5.110565,42.174800,13.880950
50%,9.313150,1.256520,143.042000,1.057620,1.392570,153.869000,1.838360,0.523607,15.006700,4.575720,...,20.077300,202.225000,11.870950,1.364510,48.995800,9.284710,3.068840,5.114230,42.311800,13.890900
75%,9.314325,1.257530,144.582500,1.069805,1.393540,154.062000,1.858995,0.523972,15.143000,4.589560,...,20.517550,202.438000,11.922350,1.366440,49.040800,9.289080,3.070680,5.117770,42.586275,13.900600
max,9.316970,1.258340,147.268000,1.073000,1.396840,154.094000,1.873130,0.525213,15.239200,4.648680,...,20.723200,202.886000,11.943900,1.370630,49.069200,9.314370,3.079010,5.129920,42.902600,13.933500

In [12]:
dd2.corr(numeric_only=True)

,Chinese Yuan,Euro,Japanese Yen,U.K. Pound Sterling,U.S. Dollar,Algerian Dinar,Australian Dollar,Bahrain Dinar,Botswana Pula,Brazilian Real,...,South African Rand,Sri Lanka Rupee,Swedish Krona,Swiss Franc,Thai Baht,Trinidad And Tobago Dollar,Tunisian Dinar,U.A.E. Dirham,Peso Uruguayo,Bolivar Fuerte
Chinese Yuan,1.000000,0.151596,0.117566,0.108695,0.291582,0.815216,0.077983,0.291926,0.467693,0.320508,...,0.356889,0.296118,-0.044773,-0.069368,0.585148,0.215925,0.542852,0.291300,0.421574,0.292168
Euro,0.151596,1.000000,-0.645719,0.531150,-0.210587,0.259964,0.331588,-0.209926,0.469668,0.383645,...,0.382248,-0.234048,0.756618,0.277528,0.370282,-0.621466,0.257016,-0.210770,-0.047889,-0.210364
Japanese Yen,0.117566,-0.645719,1.000000,-0.970308,0.210295,-0.388099,-0.582032,0.209957,-0.627015,-0.641122,...,-0.629790,0.216936,-0.484786,0.209928,-0.458043,0.952893,-0.147436,0.210296,-0.513065,0.210351
U.K. Pound Sterling,0.108695,0.531150,-0.970308,1.000000,-0.042303,0.613186,0.579213,-0.042220,0.689069,0.731765,...,0.691677,-0.063891,0.439605,-0.274110,0.484703,-0.884769,0.379161,-0.042522,0.512847,-0.042480
U.S. Dollar,0.291582,-0.210587,0.210295,-0.042303,1.000000,0.822036,0.607010,0.999999,0.580842,-0.340426,...,0.596483,0.999985,-0.671798,-0.734504,0.457371,0.135467,-0.481887,0.999999,0.665831,0.999999
Algerian Dinar,0.815216,0.259964,-0.388099,0.613186,0.822036,1.000000,0.908465,0.822349,0.883366,0.401592,...,0.910574,0.872504,-0.157963,-0.561866,0.917543,-0.321122,0.600139,0.821881,0.601316,0.822238
Australian Dollar,0.077983,0.331588,-0.582032,0.579213,0.607010,0.908465,1.000000,0.607349,0.957234,0.071958,...,0.913906,0.687806,-0.067537,-0.651600,0.769542,-0.504815,-0.677335,0.607053,0.710815,0.607077
Bahrain Dinar,0.291926,-0.209926,0.209957,-0.042220,0.999999,0.822349,0.607349,1.000000,0.581435,-0.340569,...,0.596910,0.999984,-0.671219,-0.734555,0.457699,0.135350,-0.482659,0.999999,0.666037,0.999999
Botswana Pula,0.467693,0.469668,-0.627015,0.689069,0.580842,0.883366,0.957234,0.581435,1.000000,0.220811,...,0.977147,0.671245,-0.068228,-0.707980,0.725779,-0.575553,-0.344260,0.580858,0.861270,0.581198
Brazilian Real,0.320508,0.383645,-0.641122,0.731765,-0.340426,0.401592,0.071958,-0.340569,0.220811,1.000000,...,0.249574,-0.348204,0.604634,0.172026,0.448202,-0.449111,0.935040,-0.340725,-0.001463,-0.340619
Brunei Dollar,0.499400,0.103766,-0.260258,0.325791,0.645133,0.851882,0.641138,0.645139,0.681108,0.291111,...,0.689421,0.643059,-0.252453,-0.539708,0.888381,-0.023091,0.088457,0.644950,0.822605,0.644944
Canadian Dollar,-0.186643,0.638422,-0.662233,0.670759,-0.025276,0.295338,0.422272,-0.025220,0.293106,0.422372,...,0.423738,-0.030523,0.577196,0.048658,-0.068830,-0.735402,0.259424,-0.025513,-0.060680,-0.025781
Chilean Peso,0.028821,0.242743,-0.809751,0.702740,0.465683,0.774855,0.761295,0.465498,0.677797,0.461093,...,0.731566,0.465499,0.241411,-0.470736,0.735031,-0.576629,-0.253298,0.465591,0.497600,0.465283
Czech Koruna,-0.000742,0.952136,-0.629068,0.491249,0.063391,0.406637,0.532192,0.064013,0.727982,0.270008,...,0.588378,0.061624,0.770702,0.113503,0.486452,-0.618376,0.275355,0.063353,0.815863,0.063396
Danish Krone,0.190088,0.997624,-0.668736,0.564435,-0.182763,0.311716,0.369431,-0.182083,0.518708,0.412835,...,0.431447,-0.207449,0.740096,0.232899,0.420593,-0.631611,0.250440,-0.182933,0.010790,-0.182494
Hungarian Forint,0.092517,0.500416,-0.572344,0.486629,0.401028,0.570454,0.810955,0.401776,0.937232,-0.029893,...,0.803478,0.438512,0.036164,-0.579507,0.685393,-0.543827,-0.971630,0.401323,0.835320,0.401746
Icelandic Krona,-0.094406,0.409634,-0.834549,0.760730,0.367329,0.837613,0.855761,0.367306,0.731111,0.355827,...,0.766461,0.377285,0.170161,-0.457319,0.720088,-0.750588,-0.309570,0.367261,0.683041,0.366814
Indian Rupee,0.304050,0.243851,-0.270123,0.314681,0.872862,0.923232,0.921475,0.873195,0.930798,-0.056475,...,0.897567,0.872443,-0.186991,-0.655866,0.868087,-0.186861,-0.618041,0.872859,0.758479,0.873170
Israeli New Sheqel,0.442994,0.643255,-0.798265,0.846940,0.164293,0.853723,0.602386,0.164492,0.813517,0.614313,...,0.740165,0.172577,0.384179,-0.188970,0.743116,-0.750277,0.662176,0.163922,0.685225,0.164093
Kazakhstani Tenge,-0.349278,-0.522276,0.610230,-0.497732,0.238602,-0.063087,0.005796,0.238321,-0.580269,-0.528494,...,-0.187091,0.243827,-0.368456,0.039975,-0.695504,0.495940,-0.952387,0.238915,-0.484516,0.238390
Kuwaiti Dinar,0.051050,-0.029612,0.376778,-0.492609,0.902196,0.617849,0.727243,0.902448,-0.109915,-0.691823,...,0.694096,0.902473,-0.503132,-0.656913,0.038821,0.396316,-0.448260,0.902113,NaN,0.902138
Libyan Dinar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Malaysian Ringgit,0.235758,0.462882,-0.602250,0.623274,0.470035,0.892976,0.824098,0.470234,0.807082,0.404660,...,0.913482,0.470085,0.151864,-0.327292,0.772498,-0.472334,-0.830232,0.470437,0.391256,0.469962
Mauritian Rupee,0.273543,-0.183599,0.167648,0.115298,0.946580,0.848173,0.745382,0.946419,0.735655,-0.134970,...,0.670077,0.945902,-0.585515,-0.666531,0.842505,0.063805,-0.328348,0.946318,0.958553,0.946419
Mexican Peso,0.585242,0.406158,-0.497609,0.586498,0.403862,0.740673,0.573500,0.404473,0.934872,0.300098,...,0.805283,0.432436,0.026415,-0.581990,0.635360,-0.434574,-0.403558,0.403786,0.774305,0.404680
Nepalese Rupee,-0.048039,0.247677,-0.602069,0.551789,0.641744,0.891683,0.938209,0.641833,0.913899,0.108258,...,0.819620,0.662525,-0.035216,-0.652557,0.802178,-0.488383,-0.582427,0.641691,0.727191,0.641551
New Zealand Dollar,0.158424,0.169274,0.008359,-0.105797,0.350211,0.246243,0.429160,0.351013,0.649925,-0.439459,...,0.356723,0.372515,-0.302930,-0.468039,0.321678,0.150573,-0.614821,0.350030,0.388096,0.351077
Norwegian Krone,0.011336,0.848789,-0.818583,0.728907,-0.474763,0.092266,0.155883,-0.474374,0.377984,0.662328,...,0.277324,-0.489642,0.825731,0.272323,0.186579,-0.744337,0.463579,-0.474945,-0.050926,-0.474668
Rial Omani,0.291726,-0.209931,0.209915,-0.042119,1.000000,0.822413,0.607400,1.000000,0.581392,-0.340516,...,0.596884,0.999986,-0.671271,-0.734457,0.457628,0.135184,-0.482353,0.999999,0.665990,0.999999
Pakistani Rupee,0.808891,-0.759606,0.977676,-0.550338,0.997159,0.982313,-0.250614,0.997209,-0.525282,-0.365411,...,0.230317,0.997066,-0.814961,-0.110370,-0.113615,0.686565,0.477869,0.997269,-1.000000,0.997286
Nuevo Sol,0.690147,-0.425412,-0.149566,0.330242,0.963550,0.726759,0.529584,0.963562,0.586934,0.006996,...,0.639803,0.963060,-0.833874,-0.793872,0.322008,-0.301355,1.000000,0.963534,0.842019,0.963480
Philippine Peso,0.161906,-0.314072,0.717931,-0.389512,0.203239,0.124527,-0.158866,0.202730,-0.754204,-0.104869,...,-0.260910,0.204051,-0.019277,0.342327,-0.182129,0.390251,0.054983,0.203079,-0.561318,0.202699
Polish Zloty,0.415765,0.609706,-0.806694,0.866656,0.124429,0.783491,0.592071,0.124805,0.919410,0.548924,...,0.777436,0.125998,0.283821,-0.327169,0.699110,-0.799210,0.499743,0.124251,0.796348,0.124604
Qatar Riyal,0.291630,-0.210148,0.210217,-0.042458,0.999999,0.822200,0.607177,1.000000,0.581144,-0.340877,...,0.596684,0.999986,-0.671417,-0.734487,0.457282,0.135394,-0.482729,0.999999,0.665658,0.999999
Russian Ruble,0.184050,0.348002,-0.774645,0.724416,0.521178,0.885316,0.855181,0.521161,0.875297,0.328958,...,0.867828,0.576766,0.067281,-0.490861,0.771741,-0.672200,-0.326029,0.521023,0.808170,0.520764
Saudi Arabian Riyal,0.291155,-0.210800,0.209975,-0.042236,0.999999,0.821995,0.607159,0.999999,0.581041,-0.340426,...,0.596669,0.999985,-0.671613,-0.734989,0.457309,0.135539,-0.483012,0.999999,0.665397,0.999999
Singapore Dollar,0.499400,0.103766,-0.260258,0.325791,0.645133,0.851882,0.641138,0.645139,0.681108,0.291111,...,0.689421,0.643059,-0.252453,-0.539708,0.888381,-0.023091,0.088457,0.644950,0.822605,0.644944
South African Rand,0.356889,0.382248,-0.629790,0.691677,0.596483,0.910574,0.913906,0.596910,0.977147,0.249574,...,1.000000,0.668843,-0.026316,-0.670439,0.734361,-0.545615,-0.681580,0.596590,0.731921,0.596833
Sri Lanka Rupee,0.296118,-0.234048,0.216936,-0.063891,0.999985,0.872504,0.687806,0.999984,0.671245,-0.348204,...,0.668843,1.000000,-0.672643,-0.738291,0.477133,0.160608,-0.482159,0.999985,0.804687,0.999982
Swedish Krona,-0.044773,0.756618,-0.484786,0.439605,-0.671798,-0.157963,-0.067537,-0.671219,-0.068228,0.604634,...,-0.026316,-0.672643,1.000000,0.640799,-0.018150,-0.432723,0.292028,-0.671749,-0.594228,-0.671347
Swiss Franc,-0.069368,0.277528,0.209928,-0.274110,-0.734504,-0.561866,-0.651600,-0.734555,-0.707980,0.172026,...,-0.670439,-0.738291,0.640799,1.000000,-0.392840,0.137727,0.574739,-0.734590,-0.794925,-0.734709
Thai Baht,0.585148,0.370282,-0.458043,0.484703,0.457371,0.917543,0.769542,0.457699,0.725779,0.448202,...,0.734361,0.477133,-0.018150,-0.392840,1.000000,-0.320336,-0.040216,0.457621,0.684992,0.457430
Trinidad And Tobago Dollar,0.215925,-0.621466,0.952893,-0.884769,0.135467,-0.321122,-0.504815,0.135350,-0.575553,-0.449111,...,-0.545615,0.160608,-0.432723,0.137727,-0.320336,1.000000,-0.077163,0.135382,-0.699472,0.135813
Tunisian Dinar,0.542852,0.257016,-0.147436,0.379161,-0.481887,0.600139,-0.677335,-0.482659,-0.344260,0.935040,...,-0.681580,-0.482159,0.292028,0.574739,-0.040216,-0.077163,1.000000,-0.483221,NaN,-0.483281
U.A.E. Dirham,0.291300,-0.210770,0.210296,-0.042522,0.999999,0.821881,0.607053,0.999999,0.580858,-0.340725,...,0.596590,0.999985,-0.671749,-0.734590,0.457621,0.135382,-0.483221,1.000000,0.665648,0.999999
Peso Uruguayo,0.421574,-0.047889,-0.513065,0.512847,0.665831,0.601316,0.710815,0.666037,0.861270,-0.001463,...,0.731921,0.804687,-0.594228,-0.794925,0.684992,-0.699472,NaN,0.665648,1.000000,0.665503
Bolivar Fuerte,0.292168,-0.210364,0.210351,-0.042480,0.999999,0.822238,0.607077,0.999999,0.581198,-0.340619,...,0.596833,0.999982,-0.671347,-0.734709,0.457430,0.135813,-0.483281,0.999999,0.665503,1.000000